apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: sunnylala/gatewayapp:latest
          ports:
            - containerPort: 5001
          imagePullPolicy: Always
          env:
          - name: PROFILE_HOST
            valueFrom:
              configMapKeyRef: 
                name: profile-config
                key: profile_host
          - name: TASK_HOST
            valueFrom:
              configMapKeyRef: 
                name: task-config
                key: task_host

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
spec:
  selector:
    app: gateway
  ports:
    - port: 8081
      targetPort: 5001
  type: LoadBalancer

